name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Code Checkout
        uses: actions/checkout@v3

      # 1. Docker Build
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest ./backend

      # 2. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # 3. Configure kubeconfig (EKS/any cluster)
      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # 4. Deploy to Kubernetes
      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/

      # 5. Check status
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
